# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d933eaf232c535231db9696d7e3f84e0db7d9ff1230f5e6b4e155ff95145ac50f18e3f38f4a543455db810fd6e86e28a5a9a8e3b14862815f354d0b7588d789a

test:
  secret_key_base: 4a4cc848dd05bc447e4aed68908c4cefba97b8a1e279ac82c3b81020aa83fb3cdb3847c008d8eb3fa344a0735bb5d54bc63be82284d8c3bf49fca139d2bbda5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
